### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by theluxes**

### CODE REVIEW

**Comment by RobertArendac** [comment]
Looks good but I'm going to hold off merging until I get the repo updated with the main one as lots has changed.

**Comment by RobertArendac** [comment]
Hey Jamie, so after merging with the main repo it seems like some merge conflicts were created with your pull request.  I know I had to implement some of the changes you made in order to get it working, so if you could take a look and fix the conflicts I'll merge it with the develop branch.

**Comment by theluxes** [comment]
I have merged it.

**Comment by RobertArendac** [comment]
I noticed that you included some methods into turret.h that are already inherited from Movable and Entity classes.  If you're not going to override them, I don't think they need to be included into turret.h

**Comment by RobertArendac** [comment]
Also, one more thing: it looks like you have two private sections in turret.cpp, make sure there is only one

**Pull request merged**
